name: Deploy documentation site

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

jobs:
  build:
    name: Deploys
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Build and deploy'
        shell: bash
        run: |
          sudo apt update
          sudo apt-get install build-essential procps curl file git
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
          chmod +x install.sh
          ./install.sh
          brew install doctave/doctave/doctave
          doctave build --release --allow-failed-checks

      - name: GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          build_dir: site/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}